Footer links alignement issue #36
aemsites/volvotrucks-na pull request #132
Opened 2024-11-26 18:23 UTC by santi-homps

Fix #36 

URL for testing:
- Before: https://main--volvotrucks-us--volvogroup.aem.page/
- After: https://32-VT-CA-defects--volvotrucks-us--volvogroup.aem.page/

Other markets:

Canada:
- Before: https://main--volvotrucks-ca--volvogroup.aem.page/
- After: https://32-VT-CA-defects--volvotrucks-ca--volvogroup.aem.page/

Mexico:
- Before: https://main--volvotrucks-mx--volvogroup.aem.page/
- After: https://32-VT-CA-defects--volvotrucks-mx--volvogroup.aem.page/

2024-11-26 23:19 UTC, alexiscoelho approved these changes

2024-11-26 23:25 UTC, alexiscoelho requested changes

2024-11-26 23:25 UTC, alexiscoelho commented on blocks/footer/footer.css
> +    margin: 0 0 4px;
You just need the margin-bottom, right?

2024-11-27 15:04 UTC, amglebihan approved these changes

2024-11-27 15:08 UTC, jonatan-lledo-netcentric approved these changes
Aside from the use of margin-bottom or the margin's shorthand, it's ok for me

2024-11-27 15:35 UTC, alexiscoelho requested changes

2024-11-27 15:35 UTC, alexiscoelho commented on blocks/footer/footer.css
> +    margin: 0 0 4px;
If you look the tree of the css... From where it comes, if you just change the margin bottom you are just restoring what "got lost"
If you set other margins you are setting values for margins that were not set on other viewports

2024-11-28 08:17 UTC, jonatan-lledo-netcentric approved these changes

2024-11-29 12:17 UTC, alexiscoelho approved these changes

2024-12-02 13:40 UTC, merged